version: '3'
services:
  manager-nginx:
    image: ${REGISTRY_ADDRESS}/manager-nginx:${IMAGE_TAG}
    restart: always
    depends_on:
      - manager-php-fpm
    ports:
      - 80:80
  manager-php-fpm:
    restart: always
    image: ${REGISTRY_ADDRESS}/manager-php-fpm:${IMAGE_TAG}
  manager-php-cli:
    image: ${REGISTRY_ADDRESS}/manager-php-cli:${IMAGE_TAG}
